### ISSUE TITLE
Can't determine between default or match of same locale

### ISSUE THREAD

**Issue by freeqaz** [florrain/locale#27]
If I do the following:
```
locale.Locale.default = 'en-US'
locales = new locale.Locales(supportedLocales);
locales.best('en_US')
```
I get returned 'en-US', as I expect.

The issue here is if I do something like...
```
locale.Locale.default = 'en-US'
locales = new locale.Locales(supportedLocales);
locales.best('zz-ZZ')
```
In this case, I get returned 'en-US' but that's because it didn't find a match. There is no way for me to know that I defaulted, unless I attempt to hack around it like so:
```
locale.Locale.default = 'unknown'
locales = new locale.Locales(supportedLocales);
locales.best('zz-ZZ')
```
This will return 'unknown' to me. Which I can then use to identify what happened. When coupled with this issue though -> https://github.com/jed/locale/issues/26
Now it's much not possible to understand the flow when the default is changed externally. I've got a PR open that has a possible fix, but I'm not crazy about it. There's a lot of logic for a simple goal.
https://github.com/jed/locale/pull/25
Any ideas?

**Comment by florrain** [comment]
Released version 0.1.0 that includes the fix for this.
