### ISSUE TITLE
Documentation for the Locale class API is missing

### ISSUE THREAD

**Issue by lessenadam** [florrain/locale#44]
I spent a lot of time looking for the API for a Locale object and eventually found it in the source code (though reading Coffeescript was a challenge). https://github.com/florrain/locale/blob/master/src/index.coffee#L14

Can it be in the README that a Locale object has the following properties with short descriptions of what each property entails:
- code
- defaulted
- language
- normalized
- score
- country

and methods:
- toString()
- toJSON()

**Comment by florrain** [comment]
Of course I'm open to any PRs that can improve the documentation of the package and would really appreciate it. Feel free to create one if you want to document some of those!

**Comment by lessenadam** [comment]
Done! Please check out https://github.com/florrain/locale/pull/45, thanks!

**Comment by lessenadam** [comment]
Merged #45
